# Generated by Django 4.2.4 on 2023-08-22 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Название")),
                (
                    "description",
                    models.CharField(max_length=256, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Датчик",
                "verbose_name_plural": "Датчики",
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Температура"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата измерения"
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_id",
                        to="measurement.sensor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Измерения",
                "verbose_name_plural": "Измерения",
            },
        ),
    ]
